version: "3.8"
services:
  web:
    build: .
    ports:
      - "8181:80"
    volumes:
      - ./:/app
    command: ['tail', '-f', '/dev/null']
    networks:
      - default

networks:
  default:
    external: true
    name: moodle_default
