networks:
  default:
    name: nginx_net
    external: true
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
    networks:
      - default
